defaults: &defaults
  working_directory: ~/ethstream
  docker:
    - image: circleci/node:8.9.4

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-ethstream-{{ checksum "package.json" }}
            - v2-ethstream-
      - run: yarn install
      - save_cache:
          key: v2-ethstream-{{ checksum "package.json" }}
          paths:
            ./node_modules
      - run: yarn build
      - run: yarn test
